"""empty message

Revision ID: a5387fcba485
Revises: 
Create Date: 2017-07-04 03:39:53.130341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5387fcba485'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order')
    )
    op.drop_table('excercises')
    op.drop_table('excercise')
    op.add_column('set', sa.Column('exercise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'set', 'exercise', ['exercise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'set', type_='foreignkey')
    op.drop_column('set', 'exercise_id')
    op.create_table('excercise',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('workout_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('excercise_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excercise_id'], ['excercise.id'], name='excercise_ibfk_2'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name='excercise_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('excercises',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('exercise')
    op.drop_table('exercises')
    # ### end Alembic commands ###
